on: [pull_request]

jobs:
  release_drafter_job:
    runs-on: ubuntu-latest
    name: Just Create Release
    steps:
    - name: Hello world action step
      env:
          REPO: 'LearningGit'
          OWNER: 'hengkyawijaya'
      id: hello
      uses: hengkyawijaya/release-drafter-action@v0.0.2
      with:
        github-ref: '${{github.ref}}'
        service: 'learning-git'
        prefix: 'v'
        postfix: ''
    # Use the output from the `hello` step
    - name: Release Drafter
      run: echo "execute release drafter"