name: Create Release
on:
  pull_request:
    types: [closed]

jobs:
  release_drafter_job:
    runs-on: ubuntu-latest
    name: Just Create Release
    steps:
    - name: Release Drafter
      env:
          REPO: 'LearningGit'
          OWNER: 'hengkyawijaya'
          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
      id: release_drafter
      uses: hengkyawijaya/release-drafter-action@v0.0.4
      with:
        service: 'learning-git'
        prefix: 'v'
        postfix: ''