name: Create Release
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  release_drafter_job:
    runs-on: ubuntu-latest
    name: Just Create Release
    steps:
    - name: Release Drafter
      env:
          REPO: 'LearningGit'
          OWNER: 'hengkyawijaya'
          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
      id: hello
      uses: hengkyawijaya/release-drafter-action@v0.0.2
      with:
        github-ref: '${{github.ref}}'
        service: 'learning-git'
        prefix: 'v'
        postfix: ''